* p. 5  l. 16 
  ← «a priori»
  → «Apriori»

* p. 5 l. 21
  ← «como base las implementaciones disponibles en Slatt aplicadas a»
  → «la última versión de Slatt, implementando diferentes algoritmos para:»

* p. 5 l. 23
  ← «algoritmos con aplicación a estos objetos»
  → «problemas relacionados con esta estructura de datos»
  … 

* p. 5 l. 28
  ← «encontrándose la implementación anterior en Python 2.7»
  → ∅

(Haz la traducción correspondiente en la parte en ingles)

* p. 9 l. 15

  … Falta una introducción a la mineria de datos, en donde se mencionen los siguientes hechos:
  - Mencionar que la minería de datos es un área de investigación cuyo objetivo de extraer información de grandes volúmenes de datos.
  - Entre todos los algoritmos que se utilizan, unos de los diez mas importantes son las reglas de asociación como se menciona en «Top 10 algorithms in data mining».
  - el primer algoritmo fue dado por Agrawal et al. en el artículo "Mining Association Rules between Sets of Items in Large Databases"
  - A partir de este algoritmo, se propuso el algoritmo Apriori en el artículo «Fast algorithms for mining association rules.»
  - Hay muchas librerias y programas que implementan reglas de asociación, entre ellas slatt, que ha sido usada en varios artículos :«Closure-based confidence boost in association rules» y «Closed-set-based discovery of representative association rules» y otros artículos.
  - Mencionar aquí el estado de la librería, el desfase entre utilizar python 2.7 y la cantidad de código que tiene, repetición de código, etc. Relacionarlo con el  objetivo del proyecto, que es actualizarla además de limpiar el código y mejorarle.

* p. 9 l. 19
  ← «Este proyecto se basa principalmente en reescribir slatt en Python 3»
  → «Unos de los  objetivos de este proyecto es actualizar slatt a Python 3, aprovechar las posibilidades de metaprogramación»
  … Deberías darle más realce a lo que has hecho, si no da un impresión pobre.

* p. 9 l. 21
  ← «lineas de código, y realizar una mejora en la legibilidad del propio código»
  → «lineas de código sin empeorar la legibilidad del mismo»
  … 
* p. 9 l. 22
  ← «Slatt  es un proyecto de software libre que ofrece funcionalidades para el cálculo de reglas de asociación»
  → «Las mejoras que se han hecho en  Slatt se han incorporado en un repositorio abierto, ya que la licencia de Slatt es libre. »
  … Las funcionalidades de Slatt deberían estar en la sección anterior.

* p. 9 l. 25-28
  ← «Las reglas de asociación son declaraciones .. dentro de grandes conjuntos de datos»
  → «Las reglas de asociación son expresiones del tipo $W\implies B$ donde $W, B\subset I$. El significado es que en las transacciones de la base de datos que tienen los items de $W$ tienden a tener los items en el conjunto $B$.»
  … Define antes como están definidas las reglas, empezando por definir que en una base de datos hay «transacciones», «items», «conjuntos de items» como están en las lineas 55-58. Cita el Cuadro 1 y quizás muevelo antes para facilitar al lector. Est

* p. 9 l. 26
  ← «Las medidas de evaluación de »
  → «Los parámetros esenciales para comparar»
  … Esta frase queda un poco abrupta, habría que enlazar un poco.

* p. 9 l. 59
  ← «Soporte de un itemset»
  … Si no vas a cambiar la Ilustración 1 entonces introduce la notación para soporte como $frq$. Lo mismo deberías introducir la notación para items $X,Y$ para decir que aparecen tanto los items de $X$ como de $Y$.

* p. 10 l. 20

  … Deberías poner los ejemplos usando un bloque \begin{tcolorbox} ..\end{tcolorbox}
    y añade que es un ejemplo de cálculo sobre la tabla 1.
* p. 10 l. 30
  ← «Morales y Gonzales, 2013»
  … En general es mala idea coger documentos de internet. Los tribunales suelen pensar que has cogido el primer documento que ha salido en google. Te recomendaría que todas las referencias las cambiaras. 

* p. 10 l. 29
  ← «se basa principalmente en el algoritmo Apriori»
  → «Slatt usa el algoritmo Apriori para recuperar los itemsets cuyo soporte sea mayor que un valor dado. Para resolver este problema de enumeración, Apriori utiliza una exploración en anchura entre todos los itemsets de la siguiente forma: »
  … Quizás es bueno que cites el siguiente artículo «A survey of itemset mining»


* p. 10 l. 32
  ← «Genera los itemasets ....»
  … Esta descripción no me acaba de gustar porque da muy pocos detalles.

* p. 11 l. 

  … La parte de la ingenieria de software debería estar en su propio capítulo y deberíamos extenderla.

* p. 11 l. 8-9
  ← «Para la realización del proyecto se ha utilizado una metodología incremental debido a que dicho proyecto esta dividido en diferentes partes, las cuales unas no tienen relación directa con otras, es por eso, que he decidió usar ese tipo de metodología.»
  → «Debido a la extensión de este proyecto, con gran carga teórica, se decidió usar una metodología incremental. » Aquí hay que añadir más
   … Una cosa, ¿qué diferentes partes? Falta que añadas como se implemento, ¿cuando nos reuniamos? ¿como eran las reuniones? ¿Qué hacias para organizar las reuniones?

* p. 13 

  … Falta que menciones y compares las dos implementaciones y cuales son sus diferencias.
  Sería interesante explicar por que se añaden nuevas clases. Quizás tenga más sentido hablar primero sobre la metaprogramación para que se entendiera mejor porque se crean nuevas clases.

* p. 14 

  … Cuando pones el diagrama de Gantt, deberías comentar más relacionado con la metodología iterativa incremental. Es que la metodología iterativa incremental se supone que hay un prototipo (que en este caso sería el programa de python2) y se va modificando poco a poco. 

* p. 16 l. 6
  ← «Charla metaprogramación MIT»
  → «Introducción a la Metaprogramación»
  … Los títulos tienen que ser explicativos.

* p. 16 l. 8

  … Empieza un poco explicando que es la metaprogramación. Decir que la metraprogramación es programar para generar código. Esto ya existe desde Lisp donde los datos pueden ser evaluados como un programa. Esta propiedad se llama Homoiconicidad, la de que cualquier programa puede ser tratado como datos y ser manipulados y ejecutados.

* p. 16 l. 10
  ← «En concreto, explica como funciona»
  → «La parte principal de la charla es la utilización de»

* p. 16 l. 11
  ← «, estos elementos son usados»
  → «. Estas características son usados»

* p. 16 l. 16
  ← «Una clase es un objeto que se utiliza para crear instancias de nuevos objetos»
  → «En general, las clases es la plantilla para la creación de objetos »
  … De la misma forma, tendrías que hablar que las metaclases se utilizan como plantilla para la creación de objetos. Estaría bien que pusieras algún ejemplo donde se vea la mejora.

* p. 16 l. 18
  ← «metainformación»
  … Esto no ha sido definido, ¿podrías poner una definición antes?

* p. 16 l. 24-32
  … El ejemplo que pones no esta puesto con listing. Tampoco veo cual es objetivo
* p. 16 l. 33
  ← «En el primer print la terminal no devuelve:... pertenece a la clase función»
  → «Este script escribe primero por la terminal... es un objeto de la clase "function"»

* p. 16 l. 43-47
  … Estos comentarios deberían estar en texto 


* p. 17 l. 7
  ← «\_\_new\_\_ es otro ejemplo de metaprogramación. Crea»
  → «El método estático \_\_new\_\_ se utiliza extensivamente en metaprogramación, ya que crea»

* p. 17 l. 7
  ← «nuevas instancias de clase y no está vinculado a una instancia de la clase»
  → «nuevos objetos, que son instancias de la clase»



* p. 17 l. 8
  ← «se llama»
  → «se invoca»


 
* p. 17 l. 23
  ← «Usos de la metaprogramación»
  … Si esta sección es tan corta, es mejor poner un parrafo dentro de la misma sección

* p. 17 l. 37
  ← «la mayoría de proyectos como este»
  → «este tipo de proyectos»
  …  Este parrafo no lo entiendo muy bien, ¿a qué te refieres con este tipo de proyectos? ¿qué entradas se tiene que generar? ¿qué salidas? ¿te refieres a lo que sería el uso de los diferentes módulos de ejecuciones? ¿las entradas serán las diferentes formas de ejecución? ¿algo así como un makefile?

* p. 17 l. 38
  ← «salidas.Por»
  → «salidas. Por»

* p. 17 l. 39
  ← «odioso»
  → «tedioso» o «repetitivo»

* p. 17  l. 42
  ← «[./missing semester, 2020]]»
  … En general no es bueno citar páginas web, pero si es necesario, ponlo como un pie de página.

* p. 19 l. 20
  ← «he realizado»
  → «se ha realizado»
  … En general, toda la memoria debería estar en tiempo presente y en forma impersonal.

* p. 19 l. 24
  ← «bordes»
  … Lo llamas aristas atrás, pero luego lo llamas bordes.

* p. 19 l. 28
  ← «Se toma como algoritmo principal»
  … No has definido que problema vamos a estudiar, ni las definiciones de lo  que son transversals. Por cierto, transversals debería estar entrecomillado porque es una traducción impropia.

* p. 19 l. 39

  … No sé si sería mejor poner otro ambiente en vez de listings, ya que no es código per se. Mejor utiliza algorithms u otro paquete, de todas formas que el algoritmo este en inglés y que no se entienda por si mismo. Cuando pongamos algo debería estar para que se entienda.

* p. 20 l. 11-17
  … ¿Esto no ha sido explicado en la primera parte? ¿no deberíamos hablar de los problemas de hipergrafos?

