##MAKEFILE##
##AUTHOR: ALEJANDRO MARTINEZ
##DATE: 26/03/2021

#Nombre_fich test python2 to python3
Nombre_fich : 

        python3 Python3/Nombre_fich.py > /TFG/tests/nombre_fich3.txt
        
        python2 Python2/Nombre_fich.py > /TFG/tests/nombre_fich2.txt
        
        diff /TFG/tests/nombre_fich3.txt TFG/tests/nombre_fich3.txt >
        /TFG/tests/diff_nombre_fich.txt
