#+TEMPLATE: Reporte para los estudiantes de TFG
#+key: weekly-progress-report
#+group: reports
#+contributor: Domingo Gomez-Perez
#+default-filename: weekly-progress-report.org

#+TITLE: Progreso Semanal (Semana 1)
#+AUTHOR: Alejandro Martínez Floranes
#+DATE: 10/06/2021

# Todas las semanas, se tiene que crear un reporte. 

* Resumen
Las reglas de asociación son objetos matemáticos empleados de forma extensa en disciplinas como la minería de datos, aprendizaje automático y representación del conocimiento, entre otros campos.
Slatt es un proyecto de software libre desarrollado por José Luis Balcázar (Universidad Politécnica de Barcelona). Ofrece funcionalidades para el cálculo de reglas de asociación. Para ello, se apoya en implementaciones del algoritmo a priori para el cálculo de clausuras, el retículo de las clausuras y, entre otras
funcionalidades,devuelve las reglas representativas para cualquier elección de los parámetros de soporte y confianza.

En este proyecto, se propone mejorar este software utilizando como base las implementaciones disponibles en Slatt
aplicadas a:

- hipergrafos y algoritmos con aplicación a estos objetos;
- cálculo de clausuras y retículos (lattices);

Este trabajo requerirá la búsqueda y análisis de algoritmos propuestos en la literatura científica sobre los puntos anteriores.

# Resuma brevemente el informe en 1-2 párrafos aquí. Este resumen debe
# describir en forma concreta los objetivos actuales. Es posible que
# quieras vincular a un archivo de proyecto que describe los objetivos
# del proyecto. 

* Resultados y discusión de la semana pasada
cambio cboost,numero lineas distintas p3 a p2,  reglas de amstrong, mirar codigo hypergrapgh.py tambien, (4 hojas por capitulo + la blanca), entrega de primera version el dia 21, capitulo de conclusiones(1 o 2 hojas).



# Use esta sección para describir lo que se completó la semana
# pasada. Siéntase libre de incluir tablas, figuras y discusión. Los
# «scripts» cortos están bien, pero los más largos deben ir en un
# apéndice con un enlace de referencia. Esta sección debería ser lo
# suficientemente completa como para que yo entienda lo que has hecho
# y lo que significa. No necesita ser excesivamente larga. Usa
# oraciones completas y un estilo de escritura científica. 



* Estado actual
Capitulo 1.- explicaiones reglas de asociacion, metodologia y requisitos y diagrama UML y GANTT
Capitulo 2.- charla de metaprogramación y explicación de la metaprogramación
Capitulo 3.- hipergrafos y problemas relacionados (explicacón teorica)
Capitulo 4.- KD trees explicaión teorica y relación con las reglas de asociación
Capitulo 5.- Metodologia de desarrollo, diferencias entre las versiones de python y cambios realizados en el código
Capitulo 6.- conclusiones


# Describe brevemente el trabajo que se ha dedicado esta semana, entre
# ellos literatura usada, experimentos, etc. Utilizar subsecciones
# para organizar tu trabajo. 


* Bibliografía consultada

# Briefly summarize one or two papers with citations you read that are related to your work. This does not need to be more than a few sentences per paper, and does not need to be more than one or two papers unless this was a major effort for the week.

# Títulos de las referencias consultadas, con un corto resumen (de dos
# parrafos máximo) sobre el contenido de la referencia.

