#+TEMPLATE: Reporte para los estudiantes de TFG
#+key: weekly-progress-report
#+group: reports
#+contributor: Domingo Gomez-Perez
#+default-filename: weekly-progress-report.org

#+TITLE: Progreso Semanal (Semana 03)
#+AUTHOR: Alejandro Martínez Floranes
#+DATE: 21/04/2021

# Todas las semanas, se tiene que crear un reporte. 


* Resumen
Las reglas de asociación son objetos matemáticos empleados de forma extensa en disciplinas como la minería de datos, aprendizaje automático y representación del conocimiento, entre otros campos.
Slatt es un proyecto de software libre desarrollado por José Luis Balcázar (Universidad Politécnica de Barcelona). Ofrece funcionalidades para el cálculo de reglas de asociación. Para ello, se apoya en implementaciones del algoritmo a priori para el cálculo de clausuras, el retículo de las clausuras y, entre otras
funcionalidades,devuelve las reglas representativas para cualquier elección de los parámetros de soporte y confianza.

En este proyecto, se propone mejorar este software utilizando como base las implementaciones disponibles en Slatt
aplicadas a:

- hipergrafos y algoritmos con aplicación a estos objetos;
- cálculo de clausuras y retículos (lattices);

Este trabajo requerirá la búsqueda y análisis de algoritmos propuestos en la literatura científica sobre los puntos anteriores.
El lenguaje de desarrollo será Python3, encontrándose la implementación anterior en Python 2.7

# Resuma brevemente el informe en 1-2 párrafos aquí. Este resumen debe
# describir en forma concreta los objetivos actuales. Es posible que
# quieras vincular a un archivo de proyecto que describe los objetivos
# del proyecto. 

* Resultados y discusión de la semana pasada
Seguir con la mejora de la clase hypergraph.py (usando la libreria copy), desarrollar la introducción explicando los principales problemas de los hipergrafos, reglas de asociación, que es la metaprogramación y los kd-trees. Explicar como funcionan los KD trees y que mejoras tendria en nuestra implementación de reglas de asciación.


# Use esta sección para describir lo que se completó la semana
# pasada. Siéntase libre de incluir tablas, figuras y discusión. Los
# «scripts» cortos están bien, pero los más largos deben ir en un
# apéndice con un enlace de referencia. Esta sección debería ser lo
# suficientemente completa como para que yo entienda lo que has hecho
# y lo que significa. No necesita ser excesivamente larga. Usa
# oraciones completas y un estilo de escritura científica. 




* Estado actual
# Describe brevemente el trabajo que se ha dedicado esta semana, entre
# ellos literatura usada, experimentos, etc. Utilizar subsecciones
# para organizar tu trabajo. 
Lectura de los tres papers sobre hipergrafos acabada, elegir mejor los requisitos RNF y RF, palabras clave definidas, introducido el capitulo sobre la metodologia de los test.

* Bibliografía consultada
# Briefly summarize one or two papers with citations you read that are related to your work. This does not need to be more than a few sentences per paper, and does not need to be more than one or two papers unless this was a major effort for the week.

Eiter, T., & Gottlob, G. (1995). Identifying the Minimal Transversals of a Hypergraph and Related Problems. SIAM Journal on Computing, 24(6), 1278–1304. https://doi.org/10.1137/S0097539793250299

Kavvadias, D. J., & Stavropoulos, E. C. (2005). An Efficient Algorithm for the Transversal Hypergraph Generation. Journal of Graph Algorithms and Applications, 9(2), 239–264. https://doi.org/10.7155/jgaa.00107

Kanté, M. M., Limouzy, V., Mary, A., & Nourine, L. (2014). On the Enumeration of Minimal Dominating Sets and Related Notions. SIAM Journal on Discrete Mathematics, 28(4), 1916–1929. https://doi.org/10.1137/120862612

# Títulos de las referencias consultadas, con un corto resumen (de dos
# parrafos máximo) sobre el contenido de la referencia.

